version: "3"

services:
  web:
#    container_name: web
    build: ./django
    volumes:
      - ./django:/project
    environment:
      DJANGO_SECRET_KEY: "${DJANGO_SECRET_KEY}"
      DJANGO_SETTINGS_MODULE: "toy_django_app.dev_settings" # todo
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "8019:8019"
    depends_on:
      - db
      - redis

  db:
#    container_name: db
    restart: always
    image: postgres:13.1
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
#    container_name: redis
    restart: always
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
