services:
  web:
    environment:
      DJANGO_SETTINGS_MODULE: "toy_django_app.settings"
    ports:
      - "127.0.0.1:8019:8019"

  db:
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    ports:
      - "127.0.0.1:6379:6379"
